dist: trusty
language: node_js
node_js:
  - '8'
sudo: false
if: (tag AND tag =~ ^v) OR (commit_message =~ ^Merge\spull\srequest\s#) OR (type = pull_request)
deploy:
  -
    provider: script
    script: "bash ./deploy.sh"
    skip_cleanup: true
    true:
      branch: master
      tags: true
notifications:
  email: false
