dist: trusty
language: node_js
node_js:
 - '8'
sudo: false
deploy:
  -
    provider: script
    script: "bash ./deploy.sh"
    skip_cleanup: true
    true:
      branch: master
notifications:
  email: false
